### ISSUE TITLE
[功能请求] flomo to obsidian

### ISSUE THREAD

**Issue by NNGTHB** [metal-young/obsidian-to-flomo#1]
请问能将flomo中的笔记导入到obsidian中吗？

**Comment by kaminono** [comment]
这个插件是运行在 obsidian 上的，没有对于 flomo 的访问权限，并且 flomo 目前公开的 API 只有发布。
建议你看下 chrome 的插件，通过网页插件拿到 flomo 的数据，再调用 obsidian 的 API 保存。

**Comment by TZWX-0** [comment]
> 这个插件是运行在 obsidian 上的，没有对于 flomo 的访问权限，并且 flomo 目前公开的 API 只有发布。 建议你看下 chrome 的插件，通过网页插件拿到 flomo 的数据，再调用 obsidian 的 API 保存。

chorome上有什么插件能实现这个功能吗

**Comment by kaminono** [comment]
可以试试这个 https://chrome.google.com/webstore/detail/obsidian-clipper/mphkdfmipddgfobjhphabphmpdckgfhb?utm_source=ext_app_menu 配合网页版本的 Flomo .
