### ISSUE TITLE
Send the entire contents of the file 功能不工作

### ISSUE THREAD

**Issue by Simon-Kuo** [metal-young/obsidian-to-flomo#2]
# Bug Issue
Send the entire contents of the file 功能不工作
## Description
Send the entire contents of the file 这个功能无法实现，全文发送到flomo，显示是空白。
## Steps to Reproduce
control+P调出面板，选择Send the entire contents of the file，查看flomo，显示发送了一条空白内容。
## Expected Behavior
收到一条全文内容
## Actual Behavior
空白内容
## Environment

![Snipaste_2023-05-09_09-58-21](https://user-images.githubusercontent.com/74864832/236974950-4b91fbad-caee-48c0-ac4a-622432710734.png)

  * Operating System: WIN10
  * Obsidian Version:1.2.7
  * Plugin Version: 0.1.1

**Comment by kaminono** [comment]
问题已修复，并增加用户提示。
